#define DEBUG
#ifdef DEBUG
#define ENABLE_VIRTUAL_COM_PORT 1
#endif
#undef DFU_SUPPORT
#define ORIGIN 0x08000000
#define ORIGIN_REAL 0x08000000
#undef PINPAD_SUPPORT

#define CERTDO_SUPPORT 1
#undef HID_CARD_CHANGE_SUPPORT
#define LIFE_CYCLE_MANAGEMENT_SUPPORT 1
#undef ACKBTN_SUPPORT 
#define SERIALNO_STR_LEN 12
#undef KDF_DO_REQUIRED

#define MHZ 133